name: cargo-deny

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cargo-deny:
    uses: chrisliebaer/.github/.github/workflows/cargo-deny.yml@439c94ebfb859152c5c5424065cb7ca6f2598ea4
